version: 1

sources:
  - name: postgres
    description: 'Northwind database with pre-cleaned data'
    schema: public
    tables:
      - name: orders
      -name: order_details
      - name: customers
